version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpasswd
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
volumes:
  pg_data:
    
