FROM httpd
RUN apt-get update &&\
    apt-get install -y iputils-ping &&\
    apt-get install -y inetutils-traceroute &&\
    apt-get install -y iproute2 &&\
    apt-get install -y curl telnet dnsutils vim



